//==================================================
//     Outputs that match the input variables
//==================================================
output "secret" {
  description = "The value of the `secret` input variable."
  value       = var.secret
}
output "include_original" {
  description = "The value of the `include_original` input variable, or the default value if it wasn't provided."
  value       = var.secret
}

//==================================================
//       Outputs generated by this module
//==================================================
output "secrets_by_region" {
  description = "A map of region names to the secret (original or replica) in that region."
  value       = var.include_original ? merge(local.original_secret, local.replica_secrets) : local.replica_secrets
}
